### ISSUE TITLE
ModuleNotFoundError: No module named 'Templates'

### ISSUE THREAD

**Issue by fosghen** [Tim55667757/TKSBrokerAPI#122]
Что это и как это установить? Я установил все 'Templates' которые были возможно и ни один не подошёл. Ошибка появляется, когда просто пытаюсь запустить tksbrokerapi. Версия Python 3.9.4

**Comment by Tim55667757** [comment]
@fosghen Добрый вечер!

`Templates.py` - это одна из библиотек внутри `TKSBrokerAPI`. Она идёт вместе с пакетом и должна была установиться через стандартный `pip install` из PyPI. Возможно что-то пошло не так, или может быть у вас есть какие-либо одноименные библиотеки, или были установлены иные несовместимые версии библиотек, гадать можно долго.

Вы работаете под виндовс или линукс? В любом случае, попробуйте сначала переустановить пакет `tksbrokerapi` с принудительной переустановкой всех зависимостей: `pip3 install tksbrokerapi --upgrade --force-reinstall` (под линукс/макось, или просто `pip`, если под виндовс).

Если это не поможет, попробуйте создать отдельно виртуальное Python окружение через `venv` (или в PyCharm) и установить пакет туда той же командой (или через PyCharm).

Проверьте установку командой в консоли (внутри виртуального окружения): `tksbrokerapi --version`.

Если опять что-то пойдёт не так, попробуйте также убедиться, что у вас установлены в Python вот эти пакеты из раздела "Packet TKSBrokerAPI requirements":
- если вы устанавливаете последний релиз`TKSBrokerAPI v1.5.120`: https://github.com/Tim55667757/TKSBrokerAPI/blob/master/requirements.txt
- если вы устанавливаете одну из фича-сборок, например, `pip3 install tksbrokerapi==1.6.dev140` , то должны быть все эти зависимости: https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/requirements.txt

Конечно, эти зависимости уже были указаны при сборке пакета, но мало ли что произошло при установке локально. Может быть что-то закешировалось.

Сообщите, если что-то выше помогло, или приложите полные логи установки и укажите устанавливаемую версию.

**Comment by Tim55667757** [comment]
Протестировал, разобрался с проблемой, это не проблема платформы, а особенностей вашей локальной установки.

Кажется я понял, что у вас произошло. Скорее всего, пути от библиотек того Python, куда была установлена платформа TKSBrokerAPI, не были добавлены в системные переменные, поэтому ваша локальная ОС не смогла их найти. Нужно добавить путь до библиотеки в переменную окружения `PYTHONPATH`.

Добавил подробное описание ошибки импорта в инструкции: 
- https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/README.md#Ошибки-импорта
- https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/README_EN.md#Import-errors

Скопирую сюда в задачу тоже:

---

### Ошибки импорта

Возможно, что после запуска платформы TKSBrokerAPI вы увидите ошибку импорта такого вида:

```
  File "./tksbrokerapi/TKSBrokerAPI.py", line 105, in <module>
    from Templates import *  # Some html-templates used by reporting methods in TKSBrokerAPI module
ModuleNotFoundError: No module named 'Templates'
```

Это означает, что каталог с библиотеками для той версии Python, куда была установлена платформа, не виден в системном окружении. Нужно добавить его в переменную окружения `PYTHONPATH`. Смотрите объяснение и примеры для разных ОС [по ссылке (en)](https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html). Например, под Linux/MacOS:

```commandline
export PYTHONPATH=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tksbrokerapi
```

Чтобы не устанавливать переменную `PYTHONPATH` каждый раз при открытии терминала, можно установить её в системное окружение своей ОС.
