### ISSUE TITLE
TKSBrokerAPI- 1,6 Telegram API

### ISSUE THREAD

**Issue by Oleg444000** [Tim55667757/TKSBrokerAPI#136]
Здравствуйте. TKSBrokerAPI- 1,6

python3 TKSAVDetector.py - Необработанный ответ от Telegram API-сервера:
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}

**Comment by Tim55667757** [comment]
@Oleg444000 Добрый день! Можно чуть больше подробностей? Вы конфиг-файл заполнили по инструкции? Определили chatId? Как тут: https://github.com/Tim55667757/TKSBrokerAPI/blob/develop/docs/examples/AnomalyVolumesDetector/secrets.yaml#L14-L19

Для каждого чата с каждым конкретным человеком - свой chatId

**Comment by Oleg444000** [comment]
Спасибо. заработал!!!
